// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmHhHohiMCeqEeux6U15ydbTC_LZlEsVE',
    appId: '1:892924748159:web:3696ce82cbf0f0e45d7a4a',
    messagingSenderId: '892924748159',
    projectId: 'diary-22d35',
    authDomain: 'diary-22d35.firebaseapp.com',
    storageBucket: 'diary-22d35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoqauxyur0RyCpqPhX-oMiS9tMVMQc2NQ',
    appId: '1:892924748159:android:46368a050dfd2c865d7a4a',
    messagingSenderId: '892924748159',
    projectId: 'diary-22d35',
    storageBucket: 'diary-22d35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQId89CnB6cY4g-_0erlVPfm6QCU-hb7I',
    appId: '1:892924748159:ios:718fe57e351def215d7a4a',
    messagingSenderId: '892924748159',
    projectId: 'diary-22d35',
    storageBucket: 'diary-22d35.appspot.com',
    iosClientId: '892924748159-ia3gaefuqnee2ti7inepl4p0sk3rjs3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.diary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQId89CnB6cY4g-_0erlVPfm6QCU-hb7I',
    appId: '1:892924748159:ios:718fe57e351def215d7a4a',
    messagingSenderId: '892924748159',
    projectId: 'diary-22d35',
    storageBucket: 'diary-22d35.appspot.com',
    iosClientId: '892924748159-ia3gaefuqnee2ti7inepl4p0sk3rjs3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.diary',
  );
}
